// Learning points for all available subjects
export const subjects = [
  {
    subject: "Maths",
    description:
      "is the study of numbers, shapes, and patterns. It is essential for understanding the world around us and solving real-world problems.",
    notes: [
      "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides: a² + b² = c².",
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.",
      "The area of a circle is calculated using the formula πr², where r is the radius of the circle.",
      "The derivative of x² with respect to x is 2x, which represents the slope of the tangent line to the curve at any point.",
      "The probability of an event is calculated as the ratio of favorable outcomes to the total number of possible outcomes.",
      "The quadratic formula, x = (-b ± √(b² - 4ac)) / 2a, is used to solve quadratic equations.",
      "The sum of the angles in a triangle is always 180 degrees.",
      "A logarithm is the inverse operation of exponentiation, such that logₐ(b) = c means a^c = b.",
      "The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting from 0 and 1.",
      "A matrix is a rectangular array of numbers arranged in rows and columns, used in linear algebra to solve systems of equations.",
      "The slope of a line is calculated as the change in y divided by the change in x (rise over run).",
      "An arithmetic sequence is a sequence of numbers in which the difference between consecutive terms is constant.",
      "A geometric sequence is a sequence of numbers where each term is found by multiplying the previous term by a fixed, non-zero number.",
      "The circumference of a circle is calculated as 2πr, where r is the radius.",
      "The mean (average) of a set of numbers is calculated by dividing the sum of the numbers by the total count.",
      "The median of a set of numbers is the middle value when the numbers are arranged in order.",
      "The mode of a set of numbers is the number that appears most frequently.",
      "A parabola is the graph of a quadratic function and has a U-shaped curve.",
      "The standard deviation measures the amount of variation or dispersion in a set of values.",
      "The Cartesian coordinate system uses two perpendicular axes (x and y) to plot points in a plane.",
    ],
  },
  {
    subject: "English",
    description:
      "is the study of language, literature, and communication. It helps us express ideas, understand others, and explore the richness of human culture.",
    notes: [
      "A noun is a word that represents a person, place, thing, or idea, such as 'teacher', 'city', or 'freedom'.",
      "An adjective is a word that describes or modifies a noun, providing more information about it, such as 'blue', 'tall', or 'interesting'.",
      "The subject of a sentence is the person, place, thing, or idea that is performing the action or being described.",
      "A metaphor is a figure of speech that directly compares two unrelated things, such as 'Time is a thief'.",
      "The past tense of a verb indicates an action that has already happened, such as 'ran' for the verb 'run'.",
      "A simile is a figure of speech that compares two things using 'like' or 'as', such as 'as brave as a lion'.",
      "A pronoun is a word that takes the place of a noun, such as 'he', 'she', 'it', or 'they'.",
      "An adverb modifies a verb, adjective, or another adverb, often indicating how, when, where, or to what extent something happens.",
      "The main idea of a paragraph is the central point or message that the writer wants to convey.",
      "A compound sentence is formed by joining two independent clauses with a conjunction, such as 'and', 'but', or 'or'.",
      "An alliteration is the repetition of the same initial consonant sound in closely positioned words, such as 'Peter Piper picked a peck of pickled peppers'.",
      "A hyperbole is an exaggerated statement not meant to be taken literally, such as 'I'm so hungry I could eat a horse'.",
      "An onomatopoeia is a word that imitates the sound it represents, such as 'buzz', 'bang', or 'sizzle'.",
      "A preposition is a word that shows the relationship between a noun (or pronoun) and other words in a sentence, such as 'in', 'on', or 'under'.",
      "A conjunction is a word used to connect clauses or sentences, such as 'and', 'but', or 'because'.",
      "A homophone is a word that sounds the same as another word but has a different meaning, such as 'flower' and 'flour'.",
      "A synonym is a word that has the same or nearly the same meaning as another word, such as 'happy' and 'joyful'.",
      "An antonym is a word that has the opposite meaning of another word, such as 'hot' and 'cold'.",
      "A personification is a figure of speech where human qualities are given to animals, objects, or ideas, such as 'The wind whispered through the trees'.",
      "A theme is the central idea or message in a piece of writing, often reflecting universal truths or human experiences.",
    ],
  },
  {
    subject: "Chemistry",
    description:
      "is the study of matter, its properties, and how it interacts with energy. It explains the composition of substances and the changes they undergo.",
    notes: [
      "Water is a compound made up of two hydrogen atoms and one oxygen atom, represented by the chemical formula H₂O.",
      "The atomic number of an element is the number of protons in the nucleus of an atom, which determines the element's identity.",
      "Acids are substances that release hydrogen ions (H⁺) in solution, while bases release hydroxide ions (OH⁻).",
      "The periodic table organizes elements by increasing atomic number and groups them based on similar chemical properties.",
      "Covalent bonds are formed when two atoms share electrons to achieve a stable electron configuration.",
      "The law of conservation of mass states that matter cannot be created or destroyed in a chemical reaction.",
      "An isotope is an atom of the same element with a different number of neutrons, resulting in a different atomic mass.",
      "The pH scale measures the acidity or basicity of a solution, ranging from 0 (most acidic) to 14 (most basic).",
      "A catalyst is a substance that speeds up a chemical reaction without being consumed in the process.",
      "Electronegativity is the tendency of an atom to attract electrons in a chemical bond, with fluorine being the most electronegative element.",
      "An ionic bond is formed when one atom transfers electrons to another atom, resulting in oppositely charged ions.",
      "A chemical reaction involves the breaking and forming of bonds to create new substances.",
      "The molar mass of a compound is the sum of the atomic masses of all the atoms in its formula.",
      "Avogadro's number (6.022 × 10²³) represents the number of particles in one mole of a substance.",
      "A solution is a homogeneous mixture of two or more substances, consisting of a solute and a solvent.",
      "A precipitate is a solid that forms and separates from a liquid mixture during a chemical reaction.",
      "Endothermic reactions absorb energy, while exothermic reactions release energy.",
      "The rate of a chemical reaction can be affected by temperature, concentration, surface area, and the presence of a catalyst.",
      "A buffer is a solution that resists changes in pH when small amounts of acid or base are added.",
      "The ideal gas law (PV = nRT) relates the pressure, volume, temperature, and number of moles of a gas.",
    ],
  },
  {
    subject: "Physics",
    description:
      "is the study of matter, energy, and the fundamental forces of nature. It seeks to explain how the universe behaves.",
    notes: [
      "Force is defined as mass times acceleration (F = ma), and it is measured in newtons (N).",
      "Energy cannot be created or destroyed, only transformed from one form to another, according to the law of conservation of energy.",
      "The speed of light in a vacuum is approximately 3 × 10⁸ meters per second, denoted by the symbol c.",
      "Newton's third law of motion states that for every action, there is an equal and opposite reaction.",
      "Work is calculated as the product of force and the distance over which the force is applied (W = Fd).",
      "Kinetic energy is the energy of motion, calculated as KE = ½mv², where m is mass and v is velocity.",
      "Potential energy is the stored energy of an object due to its position or configuration, such as gravitational potential energy.",
      "The first law of thermodynamics states that the total energy of an isolated system is constant.",
      "A wave is a disturbance that transfers energy through a medium or space, and it can be mechanical or electromagnetic.",
      "Ohm's law states that the current through a conductor is directly proportional to the voltage across it and inversely proportional to its resistance (V = IR).",
      "The Doppler effect explains the change in frequency or wavelength of a wave in relation to an observer moving relative to the wave source.",
      "The law of universal gravitation states that every mass attracts every other mass in the universe, and the force is proportional to the product of their masses and inversely proportional to the square of the distance between them.",
      "The photoelectric effect demonstrates that light can behave as both a wave and a particle.",
      "The concept of inertia, introduced by Galileo and formalized by Newton, states that an object will remain at rest or in uniform motion unless acted upon by an external force.",
      "The principle of superposition states that when two or more waves overlap, the resulting wave is the sum of the individual waves.",
      "The second law of thermodynamics states that the total entropy of an isolated system can never decrease over time.",
      "The electromagnetic spectrum includes all types of electromagnetic radiation, from radio waves to gamma rays.",
      "The Heisenberg uncertainty principle states that it is impossible to simultaneously know the exact position and momentum of a particle.",
      "Schrodinger's equation describes how the quantum state of a physical system changes over time.",
      "The theory of relativity, developed by Einstein, revolutionized our understanding of space, time, and gravity.",
    ],
  },
  {
    subject: "Biology",
    description:
      "is the study of living organisms, their structure, function, growth, and evolution. It helps us understand life and its processes.",
    notes: [
      "The cell is the basic structural and functional unit of all living organisms.",
      "DNA, or deoxyribonucleic acid, carries the genetic instructions for the development and functioning of living organisms.",
      "Photosynthesis is the process by which green plants convert sunlight, carbon dioxide, and water into glucose and oxygen.",
      "The human body is composed of 206 bones, which provide structure, protection, and support for movement.",
      "Enzymes are biological catalysts that speed up chemical reactions in the body without being consumed.",
      "Mitochondria are known as the powerhouses of the cell because they produce energy in the form of ATP.",
      "The circulatory system transports oxygen, nutrients, and waste products throughout the body via blood vessels.",
      "Homeostasis is the process by which organisms maintain a stable internal environment despite external changes.",
      "The nervous system is responsible for transmitting signals between different parts of the body using neurons.",
      "Evolution is the process by which species change over time through natural selection and genetic variation.",
      "The immune system defends the body against pathogens such as bacteria, viruses, and other harmful organisms.",
      "Proteins are made up of amino acids and are essential for the structure, function, and regulation of the body's tissues and organs.",
      "The endocrine system produces hormones that regulate metabolism, growth, reproduction, and other vital functions.",
      "The process of osmosis involves the movement of water molecules across a semipermeable membrane from a region of low solute concentration to high solute concentration.",
      "Chloroplasts are organelles in plant cells that contain chlorophyll and are responsible for photosynthesis.",
      "The human genome contains approximately 20,000-25,000 genes that encode proteins essential for life.",
      "Meiosis is a type of cell division that reduces the chromosome number by half, producing four gamete cells.",
      "The process of transcription involves copying a segment of DNA into RNA, which is then used to produce proteins.",
      "Biodiversity refers to the variety of life on Earth, including the diversity of species, ecosystems, and genetic variation.",
      "The food chain represents the flow of energy and nutrients through an ecosystem, starting with producers and ending with top predators.",
    ],
  },
  {
    subject: "History",
    description:
      "is the study of past events, societies, and civilizations. It helps us understand how the world has evolved over time.",
    notes: [
      "The Great Wall of China was built over several centuries to protect against invasions from northern tribes.",
      "World War II, which lasted from 1939 to 1945, involved major global powers and resulted in significant geopolitical changes.",
      "The Renaissance was a cultural movement that began in Italy in the 14th century and emphasized art, science, and humanism.",
      "The American Declaration of Independence, signed in 1776, declared the thirteen colonies' freedom from British rule.",
      "The Industrial Revolution, which began in the 18th century, marked a shift from agrarian economies to industrialized ones.",
      "The French Revolution (1789–1799) led to the overthrow of the monarchy and the rise of democratic ideals in France.",
      "The Roman Empire was one of the most powerful civilizations in history, lasting from 27 BC to AD 476 in the West.",
      "The Cold War (1947–1991) was a period of political tension and military rivalry between the United States and the Soviet Union.",
      "The abolition of slavery in the United States was achieved with the 13th Amendment to the Constitution in 1865.",
      "The fall of the Berlin Wall in 1989 symbolized the end of the Cold War and the reunification of Germany.",
      "The Magna Carta, signed in 1215, limited the powers of the English monarchy and laid the foundation for modern democracy.",
      "The American Civil War (1861–1865) was fought between the Northern states (Union) and the Southern states (Confederacy) over issues including slavery and states' rights.",
      "The Age of Exploration (15th–17th centuries) saw European powers exploring and colonizing new territories across the globe.",
      "The Treaty of Versailles, signed in 1919, officially ended World War I and imposed heavy reparations on Germany.",
      "The Black Death, a devastating pandemic in the 14th century, killed an estimated 25–30 million people in Europe.",
      "The Ottoman Empire, which lasted from 1299 to 1923, was one of the largest and most influential empires in history.",
      "The Enlightenment (17th–18th centuries) was an intellectual movement that emphasized reason, science, and individual rights.",
      "The Bolshevik Revolution of 1917 led to the establishment of the Soviet Union and the rise of communism in Russia.",
      "The United Nations was established in 1945 to promote international cooperation and prevent future conflicts.",
      "The Space Race between the United States and the Soviet Union during the Cold War led to significant advancements in space exploration, including the moon landing in 1969.",
    ],
  },
  {
    subject: "Economics",
    description:
      "is the study of how individuals, businesses, and governments make choices about allocating resources. It explores concepts like scarcity, supply and demand, and economic systems.",
    notes: [
      "Scarcity is the fundamental economic problem of having seemingly unlimited human wants in a world of limited resources.",
      "Supply and demand determine the price of goods and services in a market economy.",
      "Opportunity cost is the value of the next best alternative foregone when making a decision.",
      "Gross Domestic Product (GDP) measures the total value of goods and services produced in a country over a specific period.",
      "Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power.",
      "A monopoly is a market structure where a single seller dominates the market with no close substitutes for the product.",
      "Fiscal policy involves government decisions on taxation and spending to influence the economy.",
      "Monetary policy is the process by which a central bank manages the money supply and interest rates to achieve economic objectives.",
      "Elasticity measures how much the quantity demanded or supplied of a good changes in response to a change in price.",
      "Comparative advantage is the ability of a country to produce a good at a lower opportunity cost than another country.",
      "The law of diminishing returns states that adding more of one factor of production, while holding others constant, will eventually yield lower per-unit returns.",
      "A mixed economy combines elements of both market and planned economies, with both private and public sectors playing significant roles.",
      "The business cycle refers to the fluctuations in economic activity over time, including periods of expansion and contraction.",
      "Unemployment occurs when individuals who are capable of working and are actively seeking work cannot find a job.",
      "Trade allows countries to specialize in the production of goods and services they can produce most efficiently.",
      "A tariff is a tax imposed on imported goods to protect domestic industries or generate revenue.",
      "A budget deficit occurs when government spending exceeds its revenue in a given period.",
      "The balance of trade is the difference between the value of a country's exports and imports.",
      "Public goods are goods that are non-excludable and non-rivalrous, such as national defense and public parks.",
      "Externalities are the positive or negative effects of economic activities on third parties, such as pollution or education.",
    ],
  },
  {
    subject: "Literature",
    description:
      "is the study of written works, including poetry, prose, and drama. It explores themes, characters, and the human experience through storytelling.",
    notes: [
      "A metaphor is a figure of speech that directly compares two unrelated things, such as 'Time is a thief'.",
      "A simile is a figure of speech that compares two things using 'like' or 'as', such as 'as brave as a lion'.",
      "Personification is a literary device where human qualities are given to animals, objects, or ideas, such as 'The wind whispered through the trees'.",
      "An alliteration is the repetition of the same initial consonant sound in closely positioned words, such as 'Peter Piper picked a peck of pickled peppers'.",
      "A hyperbole is an exaggerated statement not meant to be taken literally, such as 'I'm so hungry I could eat a horse'.",
      "An onomatopoeia is a word that imitates the sound it represents, such as 'buzz', 'bang', or 'sizzle'.",
      "A theme is the central idea or message in a piece of writing, often reflecting universal truths or human experiences.",
      "A protagonist is the main character in a story, often facing challenges or conflicts.",
      "An antagonist is a character or force that opposes the protagonist, creating conflict in the story.",
      "Foreshadowing is a literary device where hints or clues are given about events that will occur later in the story.",
      "Irony is a contrast between expectation and reality, often used to create humor or emphasize a point.",
      "A plot is the sequence of events in a story, typically including an introduction, rising action, climax, falling action, and resolution.",
      "A setting is the time and place in which a story takes place, providing context for the events.",
      "A symbol is an object, character, or event that represents a deeper meaning or concept.",
      "Imagery is the use of descriptive language to create vivid mental pictures and appeal to the senses.",
      "A stanza is a grouped set of lines in a poem, often separated by a blank line.",
      "A sonnet is a 14-line poem with a specific rhyme scheme, often exploring themes of love or nature.",
      "Free verse is a type of poetry that does not follow a specific rhyme or meter.",
      "A narrative is a story or account of events, whether true or fictional, often told in prose or poetry.",
      "A moral is the lesson or message conveyed by a story, often reflecting ethical or philosophical principles.",
    ],
  },
  {
    subject: "Government",
    description:
      "is the study of political systems, institutions, and the principles that guide the organization of societies. It helps us understand how power and authority are exercised.",
    notes: [
      "The legislative branch of government is responsible for making laws.",
      "The executive branch enforces laws and is headed by the president or prime minister.",
      "The judicial branch interprets laws and ensures they are applied fairly.",
      "A democracy is a system of government where power is vested in the people, who rule either directly or through elected representatives.",
      "A monarchy is a form of government where a king or queen serves as the head of state, often for life.",
      "A constitution is a set of fundamental principles or established precedents that govern a country or organization.",
      "Federalism is a system of government where power is divided between a central authority and smaller political units, such as states or provinces.",
      "The rule of law is the principle that all individuals and institutions are subject to and accountable to the law.",
      "Suffrage is the right to vote in political elections.",
      "Checks and balances ensure that no single branch of government becomes too powerful by allowing each branch to limit the powers of the others.",
      "Separation of powers divides government responsibilities into distinct branches to prevent any one branch from exercising the core functions of another.",
      "A republic is a form of government in which the country is considered a public matter, and officials are elected by citizens.",
      "A dictatorship is a form of government where a single individual holds absolute power, often obtained and maintained by force.",
      "The United Nations is an international organization founded in 1945 to promote peace, security, and cooperation among nations.",
      "A bill of rights is a formal declaration of the fundamental rights and freedoms of individuals, often enshrined in a constitution.",
      "Judicial review is the power of courts to declare laws or executive actions unconstitutional.",
      "A political party is an organized group of people with similar political aims and opinions, seeking to influence public policy by getting its candidates elected.",
      "Civil rights are the rights of citizens to political and social freedom and equality.",
      "An amendment is a formal change or addition to a constitution or law.",
      "A treaty is a formal agreement between two or more countries, often concerning peace, trade, or other international relations.",
    ],
  },
  {
    subject: "Marketing",
    description:
      "is the study of promoting, selling, and distributing products or services. It focuses on understanding customer needs and creating value.",
    notes: [
      "Market segmentation involves dividing a market into distinct groups of buyers with similar needs or characteristics.",
      "The 4 Ps of marketing are Product, Price, Place, and Promotion, which form the foundation of a marketing strategy.",
      "Branding is the process of creating a unique identity for a product or company to differentiate it from competitors.",
      "Digital marketing uses online platforms like social media, email, and search engines to promote products or services.",
      "Customer relationship management (CRM) focuses on building and maintaining strong relationships with customers.",
      "A target market is a specific group of consumers that a company aims to reach with its products or services.",
      "Market research involves gathering and analyzing data about consumers, competitors, and market trends.",
      "A value proposition is a statement that explains why a customer should choose a product or service over competitors.",
      "Advertising is a paid form of communication used to promote products, services, or brands to a target audience.",
      "Public relations (PR) involves managing a company's reputation and building positive relationships with the public.",
      "Content marketing focuses on creating and sharing valuable, relevant content to attract and retain a target audience.",
      "Social media marketing leverages platforms like Facebook, Instagram, and Twitter to engage with customers and promote products.",
      "Search engine optimization (SEO) improves a website's visibility in search engine results to attract more organic traffic.",
      "Email marketing involves sending targeted messages to a group of customers or prospects to promote products or services.",
      "Influencer marketing uses individuals with a large following to promote products or services to their audience.",
      "A sales funnel represents the journey a customer takes from awareness to purchase, often visualized as a funnel shape.",
      "Pricing strategies, such as penetration pricing or premium pricing, are used to attract customers and maximize profits.",
      "Customer feedback is essential for improving products, services, and overall customer satisfaction.",
      "A marketing campaign is a coordinated series of actions designed to promote a product, service, or brand.",
      "Metrics like conversion rate, customer acquisition cost, and return on investment (ROI) are used to measure marketing success.",
    ],
  },
  {
    subject: "ICT",
    description:
      "is the study of computer systems, networking, and digital communication. It focuses on how technology is used to process, store, and share information.",
    notes: [
      "ICT involves the use of computers and other technologies to manage and process information.",
      "Networking refers to the connection of computers and devices to share resources and information.",
      "The internet is a global network of interconnected computers that enables communication and data sharing.",
      "Cloud computing allows users to store and access data and applications over the internet instead of on local devices.",
      "Cybersecurity involves protecting computer systems and networks from digital attacks and unauthorized access.",
      "A database is an organized collection of data that can be accessed, managed, and updated electronically.",
      "Programming languages, such as Python, Java, and C++, are used to create software applications.",
      "Artificial intelligence (AI) refers to the simulation of human intelligence in machines that can learn and make decisions.",
      "Machine learning is a subset of AI that enables systems to learn from data and improve over time without explicit programming.",
      "Big data refers to extremely large datasets that can be analyzed to reveal patterns, trends, and insights.",
      "A Local Area Network (LAN) connects computers within a limited area, such as a home, school, or office.",
      "A Wide Area Network (WAN) connects computers over large geographical areas, often using the internet.",
      "Digital communication includes email, instant messaging, video conferencing, and social media platforms.",
      "An operating system (OS) is software that manages computer hardware and software resources, such as Windows, macOS, or Linux.",
      "Data encryption is the process of converting information into a secure format to prevent unauthorized access.",
      "E-commerce refers to the buying and selling of goods and services over the internet.",
      "A firewall is a security system that monitors and controls incoming and outgoing network traffic based on predetermined rules.",
      "Virtual reality (VR) and augmented reality (AR) are technologies that create immersive digital experiences.",
      "The Internet of Things (IoT) refers to the network of physical devices connected to the internet, enabling them to collect and exchange data.",
      "Digital literacy is the ability to use technology effectively and responsibly in everyday life.",
    ],
  },
  {
    subject: "Commerce",
    description:
      "is the study of trade, business management, financial systems, and market structures. It focuses on the exchange of goods and services and the principles of business operations.",
    notes: [
      "Commerce involves the buying and selling of goods and services between individuals, businesses, and governments.",
      "A sole proprietorship is a business owned and operated by one individual, with no legal distinction between the owner and the business.",
      "A partnership is a business owned by two or more individuals who share profits, losses, and responsibilities.",
      "A corporation is a legal entity that is separate from its owners, providing limited liability to its shareholders.",
      "The supply chain refers to the network of individuals, organizations, resources, and activities involved in producing and delivering a product or service.",
      "E-commerce is the buying and selling of goods and services over the internet.",
      "A market is a place where buyers and sellers meet to exchange goods and services, either physically or virtually.",
      "Demand refers to the quantity of a product or service that consumers are willing and able to purchase at a given price.",
      "Supply refers to the quantity of a product or service that producers are willing and able to offer at a given price.",
      "Profit is the financial gain obtained when revenue exceeds expenses in a business operation.",
      "A balance sheet is a financial statement that shows a company's assets, liabilities, and equity at a specific point in time.",
      "A business plan is a written document that outlines a company's goals, strategies, and financial projections.",
      "Marketing involves promoting and selling products or services, including market research and advertising.",
      "A franchise is a business model where a franchisor grants a franchisee the right to operate a business using its brand and system.",
      "Insurance is a financial product that provides protection against potential financial losses or risks.",
      "A trade union is an organization of workers formed to protect and advance their rights and interests.",
      "Banking involves the management of financial transactions, including deposits, loans, and investments.",
      "A monopoly exists when a single company or entity dominates a market with no competition.",
      "Globalization refers to the increasing interconnectedness of economies, cultures, and markets worldwide.",
      "Taxation is the process by which governments collect revenue from individuals and businesses to fund public services and infrastructure.",
    ],
  },
  {
    subject: "Drawing",
    description:
      "is the study of creating precise and detailed drawings used in engineering, architecture, and design. It focuses on visualizing and communicating ideas through technical illustrations.",
    notes: [
      "Technical drawing uses standardized symbols, lines, and notations to convey information clearly.",
      "Orthographic projection represents a 3D object in 2D views, such as front, top, and side views.",
      "Isometric drawing shows a 3D object in a 2D space, with all axes drawn at equal angles (120°).",
      "Perspective drawing creates a realistic view of an object by simulating depth and distance.",
      "Dimensioning involves adding measurements to a drawing to specify the size and location of features.",
      "A section view shows the interior of an object by cutting through it and removing part of the exterior.",
      "Scale is used to represent large or small objects accurately on paper, such as 1:100 or 2:1.",
      "Hatching or cross-hatching is used in section views to indicate materials or cut surfaces.",
      "CAD (Computer-Aided Design) software is commonly used for creating technical drawings digitally.",
      "Title blocks provide essential information about a drawing, such as the title, scale, and author.",
      "Geometric construction involves creating shapes, angles, and patterns using basic tools like a compass and ruler.",
      "Tolerances specify the allowable variation in dimensions to ensure proper fit and function.",
      "Symbols and annotations are used to represent features like welds, finishes, and materials.",
      "Assembly drawings show how different parts fit together to form a complete product.",
      "Exploded views illustrate the relationship and order of assembly of various components.",
      "Plan views represent the top-down view of an object or structure, often used in architecture.",
      "Elevation views show the vertical face of an object or structure, such as a building facade.",
      "Sectional symbols indicate different materials in a section view, such as steel, wood, or concrete.",
      "Freehand sketching is used for quick visualization of ideas before creating detailed drawings.",
      "Standards like ISO and ANSI ensure consistency and accuracy in technical drawings worldwide.",
    ],
  },
];

export default subjects;
