export const subjects = [
  {
    subject: "Maths",
    description:
      "is the study of numbers, shapes, and patterns. It is essential for understanding the world around us and solving real-world problems.",
    notes: [
      "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides: a² + b² = c².",
      "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.",
      "The area of a circle is calculated using the formula πr², where r is the radius of the circle.",
      "The derivative of x² with respect to x is 2x, which represents the slope of the tangent line to the curve at any point.",
      "The probability of an event is calculated as the ratio of favorable outcomes to the total number of possible outcomes.",
      "The quadratic formula, x = (-b ± √(b² - 4ac)) / 2a, is used to solve quadratic equations.",
      "The sum of the angles in a triangle is always 180 degrees.",
      "A logarithm is the inverse operation of exponentiation, such that logₐ(b) = c means a^c = b.",
      "The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting from 0 and 1.",
      "A matrix is a rectangular array of numbers arranged in rows and columns, used in linear algebra to solve systems of equations.",
      "The slope of a line is calculated as the change in y divided by the change in x (rise over run).",
      "An arithmetic sequence is a sequence of numbers in which the difference between consecutive terms is constant.",
      "A geometric sequence is a sequence of numbers where each term is found by multiplying the previous term by a fixed, non-zero number.",
      "The circumference of a circle is calculated as 2πr, where r is the radius.",
      "The mean (average) of a set of numbers is calculated by dividing the sum of the numbers by the total count.",
      "The median of a set of numbers is the middle value when the numbers are arranged in order.",
      "The mode of a set of numbers is the number that appears most frequently.",
      "A parabola is the graph of a quadratic function and has a U-shaped curve.",
      "The standard deviation measures the amount of variation or dispersion in a set of values.",
      "The Cartesian coordinate system uses two perpendicular axes (x and y) to plot points in a plane.",
    ],
  },
  {
    subject: "English",
    description:
      "is the study of language, literature, and communication. It helps us express ideas, understand others, and explore the richness of human culture.",
    notes: [
      "A noun is a word that represents a person, place, thing, or idea, such as 'teacher', 'city', or 'freedom'.",
      "An adjective is a word that describes or modifies a noun, providing more information about it, such as 'blue', 'tall', or 'interesting'.",
      "The subject of a sentence is the person, place, thing, or idea that is performing the action or being described.",
      "A metaphor is a figure of speech that directly compares two unrelated things, such as 'Time is a thief'.",
      "The past tense of a verb indicates an action that has already happened, such as 'ran' for the verb 'run'.",
      "A simile is a figure of speech that compares two things using 'like' or 'as', such as 'as brave as a lion'.",
      "A pronoun is a word that takes the place of a noun, such as 'he', 'she', 'it', or 'they'.",
      "An adverb modifies a verb, adjective, or another adverb, often indicating how, when, where, or to what extent something happens.",
      "The main idea of a paragraph is the central point or message that the writer wants to convey.",
      "A compound sentence is formed by joining two independent clauses with a conjunction, such as 'and', 'but', or 'or'.",
      "An alliteration is the repetition of the same initial consonant sound in closely positioned words, such as 'Peter Piper picked a peck of pickled peppers'.",
      "A hyperbole is an exaggerated statement not meant to be taken literally, such as 'I'm so hungry I could eat a horse'.",
      "An onomatopoeia is a word that imitates the sound it represents, such as 'buzz', 'bang', or 'sizzle'.",
      "A preposition is a word that shows the relationship between a noun (or pronoun) and other words in a sentence, such as 'in', 'on', or 'under'.",
      "A conjunction is a word used to connect clauses or sentences, such as 'and', 'but', or 'because'.",
      "A homophone is a word that sounds the same as another word but has a different meaning, such as 'flower' and 'flour'.",
      "A synonym is a word that has the same or nearly the same meaning as another word, such as 'happy' and 'joyful'.",
      "An antonym is a word that has the opposite meaning of another word, such as 'hot' and 'cold'.",
      "A personification is a figure of speech where human qualities are given to animals, objects, or ideas, such as 'The wind whispered through the trees'.",
      "A theme is the central idea or message in a piece of writing, often reflecting universal truths or human experiences.",
    ],
  },
  {
    subject: "Chemistry",
    description:
      "is the study of matter, its properties, and how it interacts with energy. It explains the composition of substances and the changes they undergo.",
    notes: [
      "Water is a compound made up of two hydrogen atoms and one oxygen atom, represented by the chemical formula H₂O.",
      "The atomic number of an element is the number of protons in the nucleus of an atom, which determines the element's identity.",
      "Acids are substances that release hydrogen ions (H⁺) in solution, while bases release hydroxide ions (OH⁻).",
      "The periodic table organizes elements by increasing atomic number and groups them based on similar chemical properties.",
      "Covalent bonds are formed when two atoms share electrons to achieve a stable electron configuration.",
      "The law of conservation of mass states that matter cannot be created or destroyed in a chemical reaction.",
      "An isotope is an atom of the same element with a different number of neutrons, resulting in a different atomic mass.",
      "The pH scale measures the acidity or basicity of a solution, ranging from 0 (most acidic) to 14 (most basic).",
      "A catalyst is a substance that speeds up a chemical reaction without being consumed in the process.",
      "Electronegativity is the tendency of an atom to attract electrons in a chemical bond, with fluorine being the most electronegative element.",
      "An ionic bond is formed when one atom transfers electrons to another atom, resulting in oppositely charged ions.",
      "A chemical reaction involves the breaking and forming of bonds to create new substances.",
      "The molar mass of a compound is the sum of the atomic masses of all the atoms in its formula.",
      "Avogadro's number (6.022 × 10²³) represents the number of particles in one mole of a substance.",
      "A solution is a homogeneous mixture of two or more substances, consisting of a solute and a solvent.",
      "A precipitate is a solid that forms and separates from a liquid mixture during a chemical reaction.",
      "Endothermic reactions absorb energy, while exothermic reactions release energy.",
      "The rate of a chemical reaction can be affected by temperature, concentration, surface area, and the presence of a catalyst.",
      "A buffer is a solution that resists changes in pH when small amounts of acid or base are added.",
      "The ideal gas law (PV = nRT) relates the pressure, volume, temperature, and number of moles of a gas.",
    ],
  },
  {
    subject: "Physics",
    description:
      "is the study of matter, energy, and the fundamental forces of nature. It seeks to explain how the universe behaves.",
    notes: [
      "Force is defined as mass times acceleration (F = ma), and it is measured in newtons (N).",
      "Energy cannot be created or destroyed, only transformed from one form to another, according to the law of conservation of energy.",
      "The speed of light in a vacuum is approximately 3 × 10⁸ meters per second, denoted by the symbol c.",
      "Newton's third law of motion states that for every action, there is an equal and opposite reaction.",
      "Work is calculated as the product of force and the distance over which the force is applied (W = Fd).",
      "Kinetic energy is the energy of motion, calculated as KE = ½mv², where m is mass and v is velocity.",
      "Potential energy is the stored energy of an object due to its position or configuration, such as gravitational potential energy.",
      "The first law of thermodynamics states that the total energy of an isolated system is constant.",
      "A wave is a disturbance that transfers energy through a medium or space, and it can be mechanical or electromagnetic.",
      "Ohm's law states that the current through a conductor is directly proportional to the voltage across it and inversely proportional to its resistance (V = IR).",
      "The Doppler effect explains the change in frequency or wavelength of a wave in relation to an observer moving relative to the wave source.",
      "The law of universal gravitation states that every mass attracts every other mass in the universe, and the force is proportional to the product of their masses and inversely proportional to the square of the distance between them.",
      "The photoelectric effect demonstrates that light can behave as both a wave and a particle.",
      "The concept of inertia, introduced by Galileo and formalized by Newton, states that an object will remain at rest or in uniform motion unless acted upon by an external force.",
      "The principle of superposition states that when two or more waves overlap, the resulting wave is the sum of the individual waves.",
      "The second law of thermodynamics states that the total entropy of an isolated system can never decrease over time.",
      "The electromagnetic spectrum includes all types of electromagnetic radiation, from radio waves to gamma rays.",
      "The Heisenberg uncertainty principle states that it is impossible to simultaneously know the exact position and momentum of a particle.",
      "Schrodinger's equation describes how the quantum state of a physical system changes over time.",
      "The theory of relativity, developed by Einstein, revolutionized our understanding of space, time, and gravity.",
    ],
  },
  {
    subject: "Biology",
    description:
      "is the study of living organisms, their structure, function, growth, and evolution. It helps us understand life and its processes.",
    notes: [
      "The cell is the basic structural and functional unit of all living organisms.",
      "DNA, or deoxyribonucleic acid, carries the genetic instructions for the development and functioning of living organisms.",
      "Photosynthesis is the process by which green plants convert sunlight, carbon dioxide, and water into glucose and oxygen.",
      "The human body is composed of 206 bones, which provide structure, protection, and support for movement.",
      "Enzymes are biological catalysts that speed up chemical reactions in the body without being consumed.",
      "Mitochondria are known as the powerhouses of the cell because they produce energy in the form of ATP.",
      "The circulatory system transports oxygen, nutrients, and waste products throughout the body via blood vessels.",
      "Homeostasis is the process by which organisms maintain a stable internal environment despite external changes.",
      "The nervous system is responsible for transmitting signals between different parts of the body using neurons.",
      "Evolution is the process by which species change over time through natural selection and genetic variation.",
      "The immune system defends the body against pathogens such as bacteria, viruses, and other harmful organisms.",
      "Proteins are made up of amino acids and are essential for the structure, function, and regulation of the body's tissues and organs.",
      "The endocrine system produces hormones that regulate metabolism, growth, reproduction, and other vital functions.",
      "The process of osmosis involves the movement of water molecules across a semipermeable membrane from a region of low solute concentration to high solute concentration.",
      "Chloroplasts are organelles in plant cells that contain chlorophyll and are responsible for photosynthesis.",
      "The human genome contains approximately 20,000-25,000 genes that encode proteins essential for life.",
      "Meiosis is a type of cell division that reduces the chromosome number by half, producing four gamete cells.",
      "The process of transcription involves copying a segment of DNA into RNA, which is then used to produce proteins.",
      "Biodiversity refers to the variety of life on Earth, including the diversity of species, ecosystems, and genetic variation.",
      "The food chain represents the flow of energy and nutrients through an ecosystem, starting with producers and ending with top predators.",
    ],
  },
  {
    subject: "History",
    description:
      "is the study of past events, societies, and civilizations. It helps us understand how the world has evolved over time.",
    notes: [
      "The Great Wall of China was built over several centuries to protect against invasions from northern tribes.",
      "World War II, which lasted from 1939 to 1945, involved major global powers and resulted in significant geopolitical changes.",
      "The Renaissance was a cultural movement that began in Italy in the 14th century and emphasized art, science, and humanism.",
      "The American Declaration of Independence, signed in 1776, declared the thirteen colonies' freedom from British rule.",
      "The Industrial Revolution, which began in the 18th century, marked a shift from agrarian economies to industrialized ones.",
      "The French Revolution (1789–1799) led to the overthrow of the monarchy and the rise of democratic ideals in France.",
      "The Roman Empire was one of the most powerful civilizations in history, lasting from 27 BC to AD 476 in the West.",
      "The Cold War (1947–1991) was a period of political tension and military rivalry between the United States and the Soviet Union.",
      "The abolition of slavery in the United States was achieved with the 13th Amendment to the Constitution in 1865.",
      "The fall of the Berlin Wall in 1989 symbolized the end of the Cold War and the reunification of Germany.",
      "The Magna Carta, signed in 1215, limited the powers of the English monarchy and laid the foundation for modern democracy.",
      "The American Civil War (1861–1865) was fought between the Northern states (Union) and the Southern states (Confederacy) over issues including slavery and states' rights.",
      "The Age of Exploration (15th–17th centuries) saw European powers exploring and colonizing new territories across the globe.",
      "The Treaty of Versailles, signed in 1919, officially ended World War I and imposed heavy reparations on Germany.",
      "The Black Death, a devastating pandemic in the 14th century, killed an estimated 25–30 million people in Europe.",
      "The Ottoman Empire, which lasted from 1299 to 1923, was one of the largest and most influential empires in history.",
      "The Enlightenment (17th–18th centuries) was an intellectual movement that emphasized reason, science, and individual rights.",
      "The Bolshevik Revolution of 1917 led to the establishment of the Soviet Union and the rise of communism in Russia.",
      "The United Nations was established in 1945 to promote international cooperation and prevent future conflicts.",
      "The Space Race between the United States and the Soviet Union during the Cold War led to significant advancements in space exploration, including the moon landing in 1969.",
    ],
  },
];

export default subjects;
